# PyTorch Fundamentals
This notebook covers the fundamentals of PyTorch. 

### Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

### Creating Tensors 

    x = torch.randn(*size)              # tensor with independent N(0,1) entries
    x = torch.[ones|zeros](*size)       # tensor with all 1's [or 0's]
    x = torch.tensor(L)                 # create tensor from [nested] list or ndarray L
    y = x.clone()                       # clone of x
    with torch.no_grad():               # code wrap that stops autograd from tracking tensor history
    requires_grad=True                  # arg, when set to True, tracks computation 
                                        # history for future derivative calculations


In [2]:
# scalars have zero dimension
scalar = torch.tensor(5)
print(scalar)

tensor(5)


In [3]:
# one dimensional tensor
vector = torch.tensor([2,3])
random_vec = torch.rand(2)
vector, random_vec, vector.ndim

(tensor([2, 3]), tensor([0.6921, 0.5314]), 1)

In [4]:
# three dimensional tensor
matrix = torch.tensor([[2,3,4], [5,6,7]])
random_mat = torch.rand(2,3)
matrix, random_mat

(tensor([[2, 3, 4],
         [5, 6, 7]]),
 tensor([[0.8860, 0.7357, 0.2157],
         [0.4908, 0.5473, 0.9926]]))

In [5]:
one_to_5 = torch.arange(1, 10).reshape(3,3)
one_to_5

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
five_zeros = torch.zeros_like(one_to_5)
five_ones = torch.ones_like(one_to_5)
five_zeros, five_ones

(tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]))

### Tensor Data Types
**Note**: Tensor datatypes is one of the 3 big errors encountered in PyTorch and Deep Learning <br>
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [7]:
# creating a float32 tensor
float_32_tensor = torch.tensor([2.0, 3, 4, 5.0], dtype=torch.float32, device=None, requires_grad=False)
print(float_32_tensor, float_32_tensor.dtype)

#creating a float16 tensor
float_16_tensor = torch.tensor([2.0, 3, 4, 5.0], dtype=torch.float16, device=None, requires_grad=False)
print(float_16_tensor, float_16_tensor.dtype)

# mutliplying diff dtype tensors
float_32_tensor * float_16_tensor 

tensor([2., 3., 4., 5.]) torch.float32
tensor([2., 3., 4., 5.], dtype=torch.float16) torch.float16


tensor([ 4.,  9., 16., 25.])

### Manipulating Tensors
- Addition `torch.add()`
- Subraction `torch.sub()`
- Multiplication (element-wise) `torch.mul()`
- Division `torch.div()`
- Matrix Multiplication `torhc.matmul()`

**Types of Operation:**
- Inplace Operarion
- Out-of-place operation

In [8]:
# Addition
some_tensor = torch.tensor([2,3,4,5,6])
some_tensor2 = torch.tensor([1,1,1,1,1])
print(some_tensor)
print(some_tensor + 3)  # broadcasting 
print(torch.add(some_tensor, 3))
print(torch.add(some_tensor, some_tensor2))



tensor([2, 3, 4, 5, 6])
tensor([5, 6, 7, 8, 9])
tensor([5, 6, 7, 8, 9])
tensor([3, 4, 5, 6, 7])


In [9]:
# subraction
print(some_tensor - 1)
print(torch.sub(some_tensor, 1))
print(torch.sub(some_tensor, some_tensor2))
torch.sub

tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])


<function torch._VariableFunctionsClass.sub>

In [10]:
# multiplication 
print(some_tensor * 2) # broadcasting
print(torch.multiply(some_tensor, 2))  # # broadcasting
print(torch.matmul(some_tensor, some_tensor2))  # matmul --> dot product

tensor([ 4,  6,  8, 10, 12])
tensor([ 4,  6,  8, 10, 12])
tensor(20)


In [11]:
# multiplication in higher dimensions
some_matrix1 = torch.arange(1,5).reshape(2,2)
some_matrix2 = torch.arange(5,9).reshape(2,2)

print(f'matrix_1: \n{some_matrix1}\nmatrix_2: \n{some_matrix2}')
print(f'Element-wise Product:\n{torch.mul(some_matrix1, some_matrix2)}')
print(f'Dot Product with matmul:\n{torch.matmul(some_matrix1, some_matrix2)}')
print(f'Dot Product with Mat A @ Mat B: \n{some_matrix1 @ some_matrix2}')

matrix_1: 
tensor([[1, 2],
        [3, 4]])
matrix_2: 
tensor([[5, 6],
        [7, 8]])
Element-wise Product:
tensor([[ 5, 12],
        [21, 32]])
Dot Product with matmul:
tensor([[19, 22],
        [43, 50]])
Dot Product with Mat A @ Mat B: 
tensor([[19, 22],
        [43, 50]])


In [12]:
# Inplace operation
some_tensor2.add_(some_tensor)

tensor([3, 4, 5, 6, 7])

### Tensor Aggregation (finding min, max, sum, etc)

In [13]:
# finding max
torch.max(some_matrix1), some_matrix1.max()

(tensor(4), tensor(4))

In [14]:
# Finding min
torch.min(some_matrix1), some_matrix1.min()

(tensor(1), tensor(1))

In [15]:
# for finding mean you need to change the type as it doesn't support long dtype
torch.mean(some_matrix1.type(torch.float32)), torch.mean(some_matrix2.type(torch.float32))


(tensor(2.5000), tensor(6.5000))

In [16]:
# Finding sum
torch.sum(some_matrix1), some_matrix1.sum()

(tensor(10), tensor(10))

### Finding positional min, max

In [17]:
print(f'{some_matrix1}, \n{some_matrix2}')
print(some_matrix1.argmin(), some_matrix2.argmin())
print(some_matrix1.argmax(), some_matrix2.argmax())

tensor([[1, 2],
        [3, 4]]), 
tensor([[5, 6],
        [7, 8]])
tensor(0) tensor(0)
tensor(3) tensor(3)


### Dimensionality
* Reshape - reshapes an input tensor into the defined shape `.reshape`
* View - returns a view of the input tensor into the defined shape but keeps the memory of original tensor `view`
* Stacking - combines multiple tensor on top of each other `vstack` or side by side `hstack`
* Squeezing - removes all `1` dimensions from a tensor
* Unsqueezing - add a `1`dimension to the target tensor
* Permute - return a view of the input tensor with dimensions permuted (swapped) in a certain way

    x.size()                                  # return tuple-like object of dimensions
    x = torch.cat(tensor_seq, dim=0)          # concatenates tensors along dim
    y = x.view(a,b,...)                       # reshapes x into size (a,b,...)
    y = x.view(-1,a)                          # reshapes x into size (b,a) for some b
    y = x.transpose(a,b)                      # swaps dimensions a and b
    y = x.permute(*dims)                      # permutes dimensions
    y = x.unsqueeze(dim)                      # tensor with added axis
    y = x.unsqueeze(dim=2)                    # (a,b,c) tensor -> (a,b,1,c) tensor
    y = x.squeeze()                           # removes all dimensions of size 1 (a,1,b,1) -> (a,b)
    y = x.squeeze(dim=1)                      # removes specified dimension of size 1 (a,1,b,1) -> (a,b,1)


In [18]:
x = torch.arange(1,13)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [19]:
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

In [23]:
z = x.view(3,4) # .view doesnot make changes in z but only views z with defined shape
z[:, 0] = 5
z, x # here the changes made in z also applies in x

(tensor([[ 5,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 5, 10, 11, 12]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12]))

In [44]:
x_stacked = torch.stack([x, x], dim = 0)
x_stacked

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  5, 10, 11, 12]])

In [53]:
a = torch.rand(256, 256, 3)
a.shape

torch.Size([256, 256, 3])

In [56]:
# herre the dimensions swapped, the parameters represent the swapping order of dimensions
a.permute(2, 0, 1).shape  # here the color channel is swapped at first 

torch.Size([3, 256, 256])

### Indexing 
Indexing with PyTorch is similar to that with NumPy

In [63]:
t = torch.arange(1, 10).reshape(1,3,3)
t, t.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [72]:
t[0], t[0][0], t[0][0][1] 

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(2))

In [84]:
t[:,0,:], t[:,:,1]

(tensor([[1, 2, 3]]), tensor([[2, 5, 8]]))

### PyTorch & NumPy
- To convert a NumPy array into PyTorch tensor -> `torch.from_numpy(ndarray)`
- To convert a PyTorch tensor into Numpy array -> `torch.Tensor.numpy()`

In [85]:
# converting ndarray to tensor 
narray1 = np.arange(1,10)
tensor1 = torch.from_numpy(narray)
narray, tensor1

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32))

In [90]:
# convert tensor into ndarray 
tensor2 = torch.arange(1,8)
narray2 = tensor2.numpy()
tensor2, narray2

(tensor([1, 2, 3, 4, 5, 6, 7]), array([1, 2, 3, 4, 5, 6, 7], dtype=int64))

### Reproducity (trying to take random out of random)

In [91]:
# create two random tensors 
random_tensor_A = torch.rand(3,3)
random_tensor_B = torch.rand(3,3)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.0345, 0.1118, 0.7851],
        [0.5812, 0.9450, 0.0281],
        [0.5573, 0.4904, 0.1818]])
tensor([[0.9998, 0.8840, 0.4180],
        [0.4748, 0.1802, 0.8822],
        [0.7699, 0.6050, 0.5236]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [93]:
# create a random seed
Random_seed = 42
#torch.manual_seed(Random_seed) initializes PyTorch's random number generator with the seed 42. 
torch.manual_seed(Random_seed)
random_tensor_C = torch.rand(3,3)
# torch.mamual_seed() below resets the random number generator. 
# So the sequence of random numbers generated starts from the same initial state as before.
torch.manual_seed(Random_seed)
random_tensor_D = torch.rand(3,3)
# Since the seed was reset, random_tensor_D will be identical to random_tensor_C.

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D) 

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


### Running tensors on the GPU


In [95]:
!nvidia-smi

Mon Jan  6 22:01:17 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.36                 Driver Version: 566.36         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   35C    P0             15W /   56W |       0MiB /   4096MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

#### 1. Check for GPU access with PyTorch

In [96]:
# Setup device agnostic code 
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [97]:
# count number of devices
torch.cuda.device_count()

1

#### 2. Tensors and Device (CPU/GPU)
Tensors are created on CPU by default. You can create it on GPU or move it from CPU to GPU or vice versa.

**Note**: Tensor on GPU can't be transformed into NumPy array, so it needs to be moved back to CPU before transforming.


In [98]:
# create a tensor (default on CPU)
tensor_A = torch.tensor([1,2,3,4,5])
tensor_A, tensor_A.device

(tensor([1, 2, 3, 4, 5]), device(type='cpu'))

In [100]:
# create a tensor on GPU 
tensor_on_gpu = tensor_A.to(device)
tensor_on_gpu

tensor([1, 2, 3, 4, 5], device='cuda:0')

In [106]:
# Moving tensor back to cpu 
# A tensor on GPU can't be transformed into NumPy array
tensor_back_to_CPU = tensor_on_gpu.to('cpu')
tensor_back_to_CPU, tensor_back_to_CPU.numpy()

(tensor([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5], dtype=int64))