# PyTorch

### Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch

### Generating Tensors 

In [2]:
# scalars have zero dimension
scalar = torch.tensor(5)
print(scalar)

tensor(5)


In [3]:
# one dimensional tensor
vector = torch.tensor([2,3])
random_vec = torch.rand(2)
vector, random_vec, vector.ndim

(tensor([2, 3]), tensor([0.6183, 0.4311]), 1)

In [4]:
# three dimensional tensor
matrix = torch.tensor([[2,3,4], [5,6,7]])
random_mat = torch.rand(2,3)
matrix, random_mat

(tensor([[2, 3, 4],
         [5, 6, 7]]),
 tensor([[0.4168, 0.5332, 0.7898],
         [0.0479, 0.6043, 0.7006]]))

In [5]:
one_to_5 = torch.arange(1, 10).reshape(3,3)
one_to_5

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
five_zeros = torch.zeros_like(one_to_5)
five_ones = torch.ones_like(one_to_5)
five_zeros, five_ones

(tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
 tensor([[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]))

### Tensor Data Types
**Note**: Tensor datatypes is one of the 3 big errors encountered in PyTorch and Deep Learning <br>
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [7]:
# creating a float32 tensor
float_32_tensor = torch.tensor([2.0, 3, 4, 5.0], dtype=torch.float32, device=None, requires_grad=False)
print(float_32_tensor, float_32_tensor.dtype)

#creating a float16 tensor
float_16_tensor = torch.tensor([2.0, 3, 4, 5.0], dtype=torch.float16, device=None, requires_grad=False)
print(float_16_tensor, float_16_tensor.dtype)

# mutliplying diff dtype tensors
float_32_tensor * float_16_tensor 

tensor([2., 3., 4., 5.]) torch.float32
tensor([2., 3., 4., 5.], dtype=torch.float16) torch.float16


tensor([ 4.,  9., 16., 25.])

### Manipulating Tensors
- Addition `torch.add()`
- Subraction `torch.sub()`
- Multiplication (element-wise) `torch.mul()`
- Division `torch.div()`
- Matrix Multiplication `torhc.matmul()`

**Types of Operation:**
- Inplace Operarion
- Out-of-place operation

In [8]:
# Addition
some_tensor = torch.tensor([2,3,4,5,6])
some_tensor2 = torch.tensor([1,1,1,1,1])
print(some_tensor)
print(some_tensor + 3)  # broadcasting 
print(torch.add(some_tensor, 3))
print(torch.add(some_tensor, some_tensor2))



tensor([2, 3, 4, 5, 6])
tensor([5, 6, 7, 8, 9])
tensor([5, 6, 7, 8, 9])
tensor([3, 4, 5, 6, 7])


In [9]:
# subraction
print(some_tensor - 1)
print(torch.sub(some_tensor, 1))
print(torch.sub(some_tensor, some_tensor2))
torch.sub

tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])


<function torch._VariableFunctionsClass.sub>

In [10]:
# multiplication 
print(some_tensor * 2) # broadcasting
print(torch.multiply(some_tensor, 2))  # # broadcasting
print(torch.matmul(some_tensor, some_tensor2))  # matmul --> dot product

tensor([ 4,  6,  8, 10, 12])
tensor([ 4,  6,  8, 10, 12])
tensor(20)


In [11]:
# multiplication in higher dimensions
some_matrix1 = torch.arange(1,5).reshape(2,2)
some_matrix2 = torch.arange(5,9).reshape(2,2)

print(f'matrix_1: \n{some_matrix1}\nmatrix_2: \n{some_matrix2}')
print(f'Element-wise Product:\n{torch.mul(some_matrix1, some_matrix2)}')
print(f'Dot Product with matmul:\n{torch.matmul(some_matrix1, some_matrix2)}')
print(f'Dot Product with Mat A @ Mat B: \n{some_matrix1 @ some_matrix2}')

matrix_1: 
tensor([[1, 2],
        [3, 4]])
matrix_2: 
tensor([[5, 6],
        [7, 8]])
Element-wise Product:
tensor([[ 5, 12],
        [21, 32]])
Dot Product with matmul:
tensor([[19, 22],
        [43, 50]])
Dot Product with Mat A @ Mat B: 
tensor([[19, 22],
        [43, 50]])


In [12]:
# Inplace operation
some_tensor2.add_(some_tensor)

tensor([3, 4, 5, 6, 7])

### Tensor Aggregation (finding min, max, sum, etc)

In [13]:
# finding max
torch.max(some_matrix1), some_matrix1.max()

(tensor(4), tensor(4))

In [14]:
# Finding min
torch.min(some_matrix1), some_matrix1.min()

(tensor(1), tensor(1))

In [17]:
# for finding mean you need to change the type as it doesn't support long dtype
torch.mean(some_matrix1.type(torch.float32)), torch.mean(some_matrix2.type(torch.float32))


(tensor(2.5000), tensor(6.5000))

In [19]:
# Finding sum
torch.sum(some_matrix1), some_matrix1.sum()

(tensor(10), tensor(10))

### Finding positional min, max

In [24]:
print(f'{some_matrix1}, \n{some_matrix2}')
print(some_matrix1.argmin(), some_matrix2.argmin())
print(some_matrix1.argmax(), some_matrix2.argmax())

tensor([[1, 2],
        [3, 4]]), 
tensor([[5, 6],
        [7, 8]])
tensor(0) tensor(0)
tensor(3) tensor(3)


### Reshaping, stacking, squeezing & unsqueezing tensors
* Reshape - reshapes an input tensor into the defined shape `.reshape`
* View - returns a view of the input tensor into the defined shape but keeps the memory of original tensor `view`
* Stacking - combines multiple tensor on top of each other `vstack` or side by side `hstack`
* Squeezing - removes all `1` dimensions from a tensor
* Unsqueezing - add a `1`dimension to the target tensor
* Permute - return a view of the input tensor with dimensions permuted (swapped) in a certain way